name: Bug Report
description: Report a bug or unexpected behavior
title: "BUG: "
labels: ["bug", "Needs Triage"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have checked that this issue has not already been reported
          required: true
        - label: I have confirmed this bug exists on the latest version of kanoa
          required: true
        - label: I have confirmed this bug exists on the main branch of kanoa
          required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install kanoa version X.Y.Z
        2. Run the following code...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if applicable.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        ```python
        from kanoa import AnalyticsInterpreter

        # Your code here
        ```
      render: python
    validations:
      required: false

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Which backend(s) does this affect?
      multiple: true
      options:
        - gemini
        - claude
        - openai
        - vllm
        - All backends
        - Not backend-specific
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: |
        Please paste the output of:
        ```python
        import kanoa, sys
        print(f"kanoa: {kanoa.__version__}")
        print(f"Python: {sys.version}")
        ```
      placeholder: |
        kanoa: 0.1.4
        Python: 3.11.5
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., environment details, workarounds tried, etc.)
    validations:
      required: false
